name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Terraform Plan Destroy & Apply Destroy Plan
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Inject SSH public key from secret
        run: |
          mkdir -p tfvars
          echo 'public_key = "${{ secrets.ID_RSA }}"' > tfvars/ssh_key.auto.tfvars
          cat tfvars/ssh_key.auto.tfvars

      - name: Create tfplan directory
        run: mkdir -p tfplan

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -var-file=tfvars/ssh_key.auto.tfvars -out=tfplan/plan.destroy.tfplan

      - name: Upload Destroy Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-destroy-plan
          path: tfplan/plan.destroy.tfplan

      - name: Terraform Destroy
        run: terraform apply -auto-approve -var-file=tfvars/ssh_key.auto.tfvars tfplan/plan.destroy.tfplan
