name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Terraform Init & Destroy (Azure Backend)
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      TF_VAR_ssh_key: ${{ secrets.ID_RSA }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init (Azure Backend)
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
